<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_payee.address.zipCode</name>
   <tag></tag>
   <elementGuidId>f5111f5b-11bf-4950-854a-9b421d0ebece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.address.zipCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.address.zipCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;payee\.address\.zipCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e61f92d-70c5-46fa-8da9-0a81033d560d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e174cfbb-3c21-4196-a2e6-7ad17874b48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.address.zipCode</value>
      <webElementGuid>b6813fd4-8a2b-4542-85fa-e312a1d5723d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billpayForm&quot;)/form[1]/table[@class=&quot;form2&quot;]/tbody[1]/tr[5]/td[2]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>f3c8d796-6693-4d7f-9485-070eb4532300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.address.zipCode']</value>
      <webElementGuid>dee5ffac-99ea-4712-afcb-8554f20c53ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billpayForm']/form/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>c1320d5f-cc9f-4a95-8caa-632b2416f000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/input</value>
      <webElementGuid>89b4339c-dbcd-4e9a-8df9-d646ee3eb1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.address.zipCode']</value>
      <webElementGuid>e5f37336-0baf-4e4e-b9b1-63d42963523b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
